battle {
  token: ${?TOKEN}
  db {
    url: ${?DB_URL}
    user: ${?DB_USER}
    password: ${?DB_PASSWORD}
  }
  liquibase: ${common.liquibase}
}

local {
  token: "token"
  db {
    url: "jdbc:postgresql://localhost:5432/db_name"
    user: "postgres"
    password: "postgres"
  }
  liquibase: ${common.liquibase}
}

common {
  liquibase {
    path: "db/changelog.xml"
  }
}